#ifndef STATE_IDENTIFIERS_HPP_
#define STATE_IDENTIFIERS_HPP_

enum class StatesID {
    TITLE,
    MENU,
    GAME,
    PAUSE,
    INIT,
    MOVE,
    POST_MOVE,
    BLOODY_FATALITY,
    MOVE_TRANSITION,
    GAME_OVER,
    WEAPON_SELECT,
    INIT_MULTIPLAYER,
    MULTIPLAYER_GAME,
};

#endif // STATE_IDENTIFIERS_HPP_
