#ifndef EVENT_TYPE_HPP
#define EVENT_TYPE_HPP

enum class EventType {
    EXPLOSION,
    COLLISION,
    DESTRUCTION,
    LAUNCH_PROJECTILE,
    MOVE_LEFT,
    MOVE_RIGHT,
    CHANGE_ANGLE_UP,
    CHANGE_ANGLE_DOWN,
    JUMP_FORWARD,
    JUMP_BACKWARD,
    BEGIN_CHARGE_WEAPON,
    ZOOM_IN,
    ZOOM_OUT,
};

#endif
